export const PORTFOLIO_DATA = {
  name: "Joshua Hyunbin Lee",
  tagline: "Undergrad Student @ KAIST",
  contacts: [
    { kind: "email", label: "Email", value: "jshyunbin@gmail.com", href: "mailto:jshyunbin@gmail.com" },
    { kind: "github", label: "GitHub", value: "github.com/jshyunbin", href: "https://www.github.com/jshyunbin" },
    { kind: "linkedin", label: "LinkedIn", value: "linkedin.com/in/jhyunbin", href: "https://www.linkedin.com/in/jhyunbin" },
    { kind: "location", label: "Based in", value: "Seoul, KR" },
  ],
  education: [
    {
      year: "2021 — 2027",
      sub: "Expected Feb 2027",
      org: "KAIST",
      sub2: "Korea Advanced Institute of Science and Technology",
      role: "B.S. Computer Science · Minor, Mathematical Sciences",
      desc: "Coursework in AI/ML, Reinforcement Learning, Algorithms & Data Structures, Probability & Statistics, Computer Architecture, Operating Systems, Linear Algebra, Differential Equations, Programming Languages.",
      tags: ["CS", "Math", "AI/ML"],
    },
    {
      year: "2023 Summer",
      sub: "Summer Program",
      org: "Institute of Science Tokyo",
      sub2: "Formerly Tokyo Tech",
      role: "Undergraduate Summer Researcher",
      desc: 'Participated in the "Social Resilience and Technology" summer program — exploring how engineering systems and policy interact in disaster-prone urban contexts.',
      tags: ["Research", "Tokyo"],
    },
    {
      year: "2022 Fall",
      sub: "Exchange",
      org: "Georgia Institute of Technology",
      sub2: "Atlanta, GA",
      role: "Undergraduate Exchange · Computer Science",
      desc: "Semester exchange focused on systems and theory coursework alongside Georgia Tech's CS undergraduates.",
      tags: ["Exchange", "CS"],
    },
    {
      year: "2018 — 2020",
      sub: "Highschool",
      org: "Gyeonggi Science High School for the Gifted",
      sub2: "One of six gifted-science high schools in Korea",
      role: "Diploma · Mathematics & Science Track",
      desc: "Selective gifted-science high school — accelerated curriculum in mathematics, physics, biology, and independent research.",
      tags: ["Gifted", "Research"],
    },
  ],
  experience: [
    {
      year: "Dec 2025 — Now",
      sub: "Ongoing",
      org: "IRSL @ KAIST",
      sub2: "Interactive Robotics & Systems Lab",
      role: "Undergraduate Research Intern",
      desc: "Designing and implementing a Universal Manipulation Interface (UMI) tailored to the lab's robotic manipulation setup — bridging teleoperated demonstrations and policy learning.",
      tags: ["Robotics", "UMI", "ROS"],
    },
    {
      year: "Dec 2023 — Jun 2025",
      sub: "Mandatory Service",
      org: "KATUSA, U.S. Army",
      sub2: "Camp Humphreys",
      role: "Sergeant · Korean Augmentation to the U.S. Army",
      desc: "Led KATUSA soldiers in a bilingual U.S. Army unit; managed cross-cultural operations and communication between Korean and American personnel during 18 months of mandatory service.",
      tags: ["Leadership", "Bilingual"],
    },
    {
      year: "2023 Spring",
      sub: "Semester",
      org: "Daedeok Software Meister H.S.",
      sub2: "Daejeon, KR",
      role: "Teaching Assistant",
      desc: "Delivered lectures and guided lab sessions on big-data analysis using NumPy, pandas, Matplotlib, and Plotly — supporting ~30 high-school students through their term projects.",
      tags: ["Teaching", "Python"],
    },
    {
      year: "Dec 2022 — Feb 2023",
      sub: "Internship",
      org: "Rainbow Brain",
      sub2: "Seoul, KR",
      role: "Software Engineer Intern",
      desc: "Developed an RPA system automating end-to-end e-commerce review analysis — data scraping, keyword extraction, sentiment analysis, and visualization — driven by language models.",
      tags: ["RPA", "NLP", "LLM"],
    },
  ],
  skills: [
    { group: "Languages", items: ["Python", "C / C++", "TypeScript", "Java", "Rust"] },
    { group: "Frameworks", items: ["PyTorch", "NumPy", "pandas", "React"] },
    { group: "Tools", items: ["Docker", "ROS", "MuJoCo", "robosuite"] },
  ],
  spoken: [
    { lang: "Korean", note: "Native", level: 1.0 },
    { lang: "English", note: "TOEFL 104", level: 0.86 },
    { lang: "Japanese", note: "JLPT N2", level: 0.62 },
  ],
  hobbies: [
    { title: "Films & Anime", note: "Late-night rewatches.", detail: "Akira, Fight Club, Satoshi Kon. Keeping a running list of opening shots that ruined me.", icon: "film" },
    { title: "Café Hunting", note: "Specialty roasters in Seoul · Daejeon.", detail: "Maps pinned with espresso temps and notes on the wifi situation. Currently chasing the perfect cortado.", icon: "coffee" },
    { title: "My Cats", note: "Two of them. Loud, fluffy.", detail: "Bori (long-haired tabby, full-time biscuit-maker) and Jjoongie (snowshoe, drool specialist).", icon: "cat" },
    { title: "Games", note: "Indies, roguelikes, anything Kirby.", detail: "Hades, Hollow Knight, Outer Wilds. I will absolutely lose an evening to a well-tuned dash.", icon: "controller" },
  ],
  projects: [
    {
      title: "ShapeBind",
      sub: "Introducing Shape into Unified Embedding Space",
      desc: "Demonstrated that binding shape and text with rich semantic information creates a high-quality embedding space — enabling shape editing through latent-space interpolation guided by multi-modal prompts.",
      stack: ["PyTorch", "Python", "Multi-modal"],
      year: "2023",
    },
    {
      title: "Protein Sequence Design",
      sub: "via Reinforcement Learning",
      desc: "Built a framework that generates protein sequences which are both stable and functional by modeling sequence design as a Markov Decision Process. Achieved ~8% improvement over baseline fitness scores using PPO.",
      stack: ["PyTorch", "Python", "RL · PPO"],
      year: "2023",
    },
  ],
};

